# Test!Test!est!
name: test-build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  # Pester test job
  pester-test:
    runs-on: windows-2019
    steps:
      # checkout
      - uses: actions/checkout@v2
      # Runs Pester all *.tests.ps1 scripts
      - name: Run Pester tests
        run: |
          Get-InstalledModule
          Get-Module
          # Write-Output "Run Pester $(Get-InstalledModule Pester | Select-Object -ExpandProperty Version) ..."
        shell: pwsh
